# Generated by Django 5.2.4 on 2025-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vid_id", models.TextField()),
                ("title", models.TextField()),
                ("transcript", models.TextField()),
                ("category_1", models.TextField()),
                ("category_2", models.TextField()),
                ("task_id", models.TextField()),
                ("punctuated", models.BooleanField()),
                ("transcript_num_chars", models.IntegerField()),
                ("default_language", models.TextField()),
                ("default_audio_language", models.TextField()),
            ],
        ),
    ]
