# Generated by Django 5.2.4 on 2025-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_url",
            field=models.TextField(default="-"),
            preserve_default=False,
        ),
    ]
