services:
  postgres-db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=swaq_ai_db
    ports:
      - "5434:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
